import { describe, expect, test } from "bun:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CouncilStore } from "../src/council/store";

function fixture() { const root = mkdtempSync(join(tmpdir(), "council-store-")); const store = new CouncilStore(join(root, "state.json")); store.joinAgent({ id: "alice", name: "Alice", role: "Architect" }); store.joinAgent({ id: "bob", name: "Bob", role: "Critic" }); store.ensureRoom({ id: "nolane", name: "Nolane Core", mission: "Agree on an implementation policy." }); return { root, store }; }

describe("CouncilStore", () => {
  test("persists threaded discussion and restores it", () => { const { root, store } = fixture(); try { const proposal = store.say({ roomId: "nolane", authorAgentId: "alice", kind: "proposal", body: "Use architecture X", mentions: ["bob"] }); const reply = store.say({ roomId: "nolane", authorAgentId: "bob", body: "X has a race", replyTo: proposal.id }); expect(reply.threadId).toBe(proposal.threadId); const reopened = new CouncilStore(join(root, "state.json")); expect(reopened.readRoom("nolane", 10).map(message => message.body)).toEqual(["Use architecture X", "X has a race"]); } finally { rmSync(root, { recursive: true, force: true }); } });
  test("builds a bounded resurrection packet for a woken agent", () => { const { root, store } = fixture(); try { store.checkpoint({ agentId: "alice", roomId: "nolane", summary: "I proposed X; rollback is unresolved." }); const source = store.say({ roomId: "nolane", authorAgentId: "bob", body: "Blocking flaw: rollback corrupts state", mentions: ["alice"] }); const wake = store.wake({ targetAgentId: "alice", sourceAgentId: "bob", roomId: "nolane", sourceMessageId: source.id, reason: "Resolve the rollback flaw" }); const packet = store.buildContextPacket({ agentId: "alice", roomId: "nolane", wakeId: wake.id }); expect(packet.identity.id).toBe("alice"); expect(packet.wake?.reason).toContain("rollback"); expect(packet.checkpoint?.summary).toContain("proposed X"); expect(packet.recentMessages.at(-1)?.body).toContain("Blocking flaw"); } finally { rmSync(root, { recursive: true, force: true }); } });
  test("tracks decisions and assigned work separately from chat", () => { const { root, store } = fixture(); try { const decision = store.decide({ roomId: "nolane", createdByAgentId: "alice", title: "Memory policy", policy: "Adopt X2", rationale: "It resolves the race", acceptedArguments: ["Bob's race objection"] }); const task = store.createTask({ roomId: "nolane", createdByAgentId: "alice", assigneeAgentId: "bob", title: "Red-team X2", description: "Attack concurrency and rollback." }); const updated = store.updateTask({ taskId: task.id, actorAgentId: "bob", status: "in_progress" }); expect(decision.policy).toBe("Adopt X2"); expect(updated.assigneeAgentId).toBe("bob"); expect(updated.status).toBe("in_progress"); } finally { rmSync(root, { recursive: true, force: true }); } });
});

describe("Council wake lifecycle", () => { test("records delivery attempts and failures without losing the wake reason", () => { const { root, store } = fixture(); try { const wake = store.wake({ targetAgentId: "alice", sourceAgentId: "bob", roomId: "nolane", reason: "Review proposal X" }); expect(wake.attempts).toBe(0); expect(store.updateWake(wake.id, "delivering").attempts).toBe(1); const failed = store.updateWake(wake.id, "failed", "browser unavailable"); expect(failed.reason).toBe("Review proposal X"); expect(failed.lastError).toContain("browser unavailable"); } finally { rmSync(root, { recursive: true, force: true }); } }); });
