import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { CouncilStore } from "./store";
import { councilMcpSessionId, type CouncilWakeDelivery } from "./mcp-shared";
import { registerCouncilDiscussionTools } from "./mcp-tools-discussion";
import { registerCouncilWorkTools } from "./mcp-tools-work";
export const COUNCIL_MCP_SERVER_NAME = "codexweb-council";
export const COUNCIL_MCP_SERVER_VERSION = "1.0.0";
export const COUNCIL_TOOL_NAMES = ["council_join", "council_room_upsert", "council_status", "council_read", "council_say", "council_reply", "council_decide", "council_task_create", "council_task_update", "council_wake", "council_checkpoint", "council_context", "council_agent_status"] as const;
export function createCouncilMcpServer(store: CouncilStore, options: { wakeDelivery?: CouncilWakeDelivery } = {}): McpServer { const server = new McpServer({ name: COUNCIL_MCP_SERVER_NAME, version: COUNCIL_MCP_SERVER_VERSION }); const bindings = new Map<string, string>(); const bindSession = (extra: unknown, agentId: string): boolean => { const sid = councilMcpSessionId(extra); if (sid) bindings.set(sid, agentId); return Boolean(sid); }; const resolveActor = (extra: unknown, explicit?: string): string => { const sid = councilMcpSessionId(extra); const bound = sid ? bindings.get(sid) : undefined; if (bound && explicit && bound !== explicit) throw new Error(`This MCP session is joined as ${bound}; refusing to act as ${explicit}`); const actor = bound ?? explicit; if (!actor) throw new Error("Join the Council first with council_join, or provide agent_id"); return actor; }; registerCouncilDiscussionTools(server, store, resolveActor, bindSession); registerCouncilWorkTools(server, store, resolveActor, options.wakeDelivery); return server; }
export async function runCouncilMcpServer(options: { storePath?: string; store?: CouncilStore; wakeDelivery?: CouncilWakeDelivery }): Promise<void> { const store = options.store ?? (options.storePath ? new CouncilStore(options.storePath) : undefined); if (!store) throw new Error("Council MCP requires a store or storePath"); await createCouncilMcpServer(store, { wakeDelivery: options.wakeDelivery }).connect(new StdioServerTransport()); }
