import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import { CouncilStore } from "./store";
import { actorSchema, agentIdSchema, bodySchema, councilMcpResult, messageIdSchema, roomIdSchema, type ResolveCouncilActor } from "./mcp-shared";

export function registerCouncilDiscussionTools(server: McpServer, store: CouncilStore, resolveActor: ResolveCouncilActor, bindSession: (extra: unknown, agentId: string) => boolean): void {
  server.registerTool("council_join", { title: "Join ChatGPT Council", description: "Register or resume a stable named ChatGPT participant and bind this MCP session to that identity.", inputSchema: { agent_id: agentIdSchema, name: z.string().trim().min(1).max(120), role: z.string().trim().min(1).max(200) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, name, role }, extra) => { const agent = store.joinAgent({ id: agent_id, name, role, status: "awake" }); const sessionBound = bindSession(extra, agent.id); return councilMcpResult({ agent, session_bound: sessionBound, next: "Read council_status and council_context before acting." }); });
  server.registerTool("council_room_upsert", { title: "Create or update a Council room", description: "Create a shared deliberation room or update its human-readable mission.", inputSchema: { ...actorSchema, room_id: roomIdSchema, name: z.string().trim().min(1).max(160), mission: z.string().trim().min(1).max(8_000) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, room_id, name, mission }, extra) => { resolveActor(extra, agent_id); return councilMcpResult({ room: store.ensureRoom({ id: room_id, name, mission }) }); });
  server.registerTool("council_status", { title: "Read Council status", description: "Read compact shared state: participants, rooms, recent decisions, active tasks and pending wake events.", inputSchema: { ...actorSchema, room_id: roomIdSchema.optional() }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, room_id }, extra) => { const actor = resolveActor(extra, agent_id); const snapshot = store.snapshot(); return councilMcpResult({ actor, agents: snapshot.agents, rooms: snapshot.rooms, decisions: snapshot.decisions.filter(item => !room_id || item.roomId === room_id).slice(-12), tasks: snapshot.tasks.filter(item => (!room_id || item.roomId === room_id) && item.status !== "done").slice(-80), pending_wakes: snapshot.wakes.filter(item => item.targetAgentId === actor && item.status === "pending").slice(-20) }); });
  server.registerTool("council_read", { title: "Read Council room", description: "Read the most recent shared room messages in chronological order.", inputSchema: { ...actorSchema, room_id: roomIdSchema, limit: z.number().int().min(1).max(200).default(40) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, room_id, limit }, extra) => { resolveActor(extra, agent_id); return councilMcpResult({ room_id, messages: store.readRoom(room_id, limit) }); });
  server.registerTool("council_say", { title: "Speak in Council", description: "Post a normal message or proposal to a shared room and optionally mention other named agents.", inputSchema: { ...actorSchema, room_id: roomIdSchema, body: bodySchema, kind: z.enum(["message", "proposal", "system"]).default("message"), mentions: z.array(agentIdSchema).max(32).default([]), thread_id: agentIdSchema.optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, room_id, body, kind, mentions, thread_id }, extra) => { const actor = resolveActor(extra, agent_id); return councilMcpResult({ message: store.say({ roomId: room_id, authorAgentId: actor, body, kind, mentions, ...(thread_id ? { threadId: thread_id } : {}) }) }); });
  server.registerTool("council_reply", { title: "Reply in Council", description: "Reply to an existing message while preserving its discussion thread.", inputSchema: { ...actorSchema, room_id: roomIdSchema, reply_to: messageIdSchema, body: bodySchema, mentions: z.array(agentIdSchema).max(32).default([]) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, room_id, reply_to, body, mentions }, extra) => { const actor = resolveActor(extra, agent_id); return councilMcpResult({ message: store.say({ roomId: room_id, authorAgentId: actor, body, mentions, replyTo: reply_to }) }); });
  server.registerTool("council_checkpoint", { title: "Save Council working memory", description: "Save compact task state for this agent so a later wake can restore continuity without replaying the whole transcript.", inputSchema: { ...actorSchema, room_id: roomIdSchema.optional(), summary: z.string().trim().min(1).max(24_000) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, room_id, summary }, extra) => { const actor = resolveActor(extra, agent_id); return councilMcpResult({ checkpoint: store.checkpoint({ agentId: actor, ...(room_id ? { roomId: room_id } : {}), summary }) }); });
  server.registerTool("council_context", { title: "Restore Council context", description: "Build the bounded resurrection packet for a participant from shared state, recent discussion and personal checkpoint.", inputSchema: { ...actorSchema, room_id: roomIdSchema, wake_id: z.string().trim().min(1).max(128).optional(), recent_limit: z.number().int().min(5).max(100).default(40) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, room_id, wake_id, recent_limit }, extra) => { const actor = resolveActor(extra, agent_id); return councilMcpResult(store.buildContextPacket({ agentId: actor, roomId: room_id, ...(wake_id ? { wakeId: wake_id } : {}), recentLimit: recent_limit })); });
  server.registerTool("council_agent_status", { title: "Set Council presence", description: "Mark the current Council participant awake, sleeping or offline.", inputSchema: { ...actorSchema, status: z.enum(["awake", "sleeping", "offline"]) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, status }, extra) => { const actor = resolveActor(extra, agent_id); return councilMcpResult({ agent: store.setAgentStatus(actor, status) }); });
}
