import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import { CouncilStore } from "./store";
import { actorSchema, agentIdSchema, assertAgentTokenNotExposed, councilMcpResult, messageIdSchema, roomIdSchema, type CouncilManagedMcpAuthorizer, type CouncilWakeDelivery, type ResolveCouncilActor } from "./mcp-shared";

export function registerCouncilWorkTools(
  server: McpServer,
  store: CouncilStore,
  resolveActor: ResolveCouncilActor,
  wakeDelivery?: CouncilWakeDelivery,
  authorizer?: CouncilManagedMcpAuthorizer,
): void {
  server.registerTool("council_task_list", { title: "List Council tasks", description: "Read bounded Council tasks filtered by room, status, or assignee.", inputSchema: { ...actorSchema, room_id: roomIdSchema.optional(), status: z.enum(["todo", "claimed", "in_progress", "review", "done", "blocked"]).optional(), assignee_agent_id: agentIdSchema.optional(), limit: z.number().int().min(1).max(200).default(80) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, agent_token, room_id, status, assignee_agent_id, limit }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); const tasks = store.snapshot().tasks.filter(task => (!room_id || task.roomId === room_id) && (!status || task.status === status) && (!assignee_agent_id || task.assigneeAgentId === assignee_agent_id)).slice(-limit); return councilMcpResult({ actor, tasks }); });
  server.registerTool("council_task_read", { title: "Read Council task", description: "Read one Council task by stable task id.", inputSchema: { ...actorSchema, task_id: z.string().trim().min(1).max(128) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, agent_token, task_id }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); const task = store.snapshot().tasks.find(item => item.id === task_id); if (!task) throw new Error("Council task does not exist"); return councilMcpResult({ actor, task }); });
  server.registerTool("council_decision_list", { title: "List Council decisions", description: "Read bounded final Council decisions, optionally scoped to one room.", inputSchema: { ...actorSchema, room_id: roomIdSchema.optional(), limit: z.number().int().min(1).max(100).default(30) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, agent_token, room_id, limit }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); const decisions = store.snapshot().decisions.filter(item => !room_id || item.roomId === room_id).slice(-limit); return councilMcpResult({ actor, decisions }); });
  server.registerTool("council_decision_read", { title: "Read Council decision", description: "Read one final Council decision including rationale, accepted/rejected arguments, and unresolved risks.", inputSchema: { ...actorSchema, decision_id: z.string().trim().min(1).max(128) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, agent_token, decision_id }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); const decision = store.snapshot().decisions.find(item => item.id === decision_id); if (!decision) throw new Error("Council decision does not exist"); return councilMcpResult({ actor, decision }); });
  server.registerTool("council_wake_list", { title: "List Council wake receipts", description: "Read bounded safe wake lifecycle receipts filtered by room, target, or active state.", inputSchema: { ...actorSchema, room_id: roomIdSchema.optional(), target_agent_id: agentIdSchema.optional(), active_only: z.boolean().default(false), limit: z.number().int().min(1).max(200).default(50) }, annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, agent_token, room_id, target_agent_id, active_only, limit }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); const wakes = store.snapshot().wakes.filter(wake => (!room_id || wake.roomId === room_id) && (!target_agent_id || wake.targetAgentId === target_agent_id) && (!active_only || ["queued", "dispatched", "target-running", "pending", "delivering"].includes(wake.status))).slice(-limit).map(wake => ({ id: wake.id, roomId: wake.roomId, sourceAgentId: wake.sourceAgentId, targetAgentId: wake.targetAgentId, sourceMessageId: wake.sourceMessageId, reason: wake.reason, status: wake.status, attempts: wake.attempts, expiresAt: wake.expiresAt, transitions: wake.transitions, createdAt: wake.createdAt, updatedAt: wake.updatedAt })); return councilMcpResult({ actor, wakes }); });

  server.registerTool("council_decide", { title: "Record final Council policy", description: "Record a deliberated policy with rationale, accepted/rejected arguments and unresolved risks. Managed participants require finalize permission and a ready decision gate.", inputSchema: { ...actorSchema, room_id: roomIdSchema, title: z.string().trim().min(1).max(240), policy: z.string().trim().min(1).max(12_000), rationale: z.string().trim().min(1).max(12_000), accepted_arguments: z.array(z.string().trim().min(1).max(2_000)).max(64).default([]), rejected_arguments: z.array(z.string().trim().min(1).max(2_000)).max(64).default([]), unresolved_risks: z.array(z.string().trim().min(1).max(2_000)).max(64).default([]) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, agent_token, room_id, title, policy, rationale, accepted_arguments, rejected_arguments, unresolved_risks }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); authorizer?.authorizeManagedDecision(actor, room_id); assertAgentTokenNotExposed(agent_token, [title, policy, rationale, accepted_arguments, rejected_arguments, unresolved_risks]); return councilMcpResult({ decision: store.decide({ roomId: room_id, createdByAgentId: actor, title, policy, rationale, acceptedArguments: accepted_arguments, rejectedArguments: rejected_arguments, unresolvedRisks: unresolved_risks }) }); });
  server.registerTool("council_task_create", { title: "Create Council work item", description: "Create a concrete task resulting from deliberation and optionally assign it to a named agent. Managed participants require assign permission.", inputSchema: { ...actorSchema, room_id: roomIdSchema, title: z.string().trim().min(1).max(240), description: z.string().trim().min(1).max(8_000), assignee_agent_id: agentIdSchema.optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, agent_token, room_id, title, description, assignee_agent_id }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); authorizer?.authorizeManaged(actor, "assign"); assertAgentTokenNotExposed(agent_token, [title, description]); return councilMcpResult({ task: store.createTask({ roomId: room_id, createdByAgentId: actor, title, description, ...(assignee_agent_id ? { assigneeAgentId: assignee_agent_id } : {}) }) }); });
  server.registerTool("council_task_update", { title: "Update Council work item", description: "Claim, advance, block, review or complete a Council task. Managed participants may update their own assignment; reassignment requires assign permission.", inputSchema: { ...actorSchema, task_id: z.string().trim().min(1).max(128), status: z.enum(["todo", "claimed", "in_progress", "review", "done", "blocked"]), assignee_agent_id: agentIdSchema.optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, agent_token, task_id, status, assignee_agent_id }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); authorizer?.authorizeManagedTaskUpdate(actor, task_id, assignee_agent_id); return councilMcpResult({ task: store.updateTask({ taskId: task_id, actorAgentId: actor, status, ...(assignee_agent_id ? { assigneeAgentId: assignee_agent_id } : {}) }) }); });
  server.registerTool("council_wake", { title: "Wake another Council participant", description: "Durably target another named participant and asynchronously schedule a ChatGPT Web resurrection turn when the wake engine is available. Managed participants require wake permission. The caller receives only the wake receipt; the target's private checkpoint/context is never returned to the caller.", inputSchema: { ...actorSchema, target_agent_id: agentIdSchema, room_id: roomIdSchema, reason: z.string().trim().min(1).max(4_000), source_message_id: messageIdSchema.optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, agent_token, target_agent_id, room_id, reason, source_message_id }, extra) => { const actor = resolveActor(extra, agent_id, agent_token); authorizer?.authorizeManaged(actor, "wake"); assertAgentTokenNotExposed(agent_token, [reason]); const wake = store.wake({ targetAgentId: target_agent_id, sourceAgentId: actor, roomId: room_id, reason, ...(source_message_id ? { sourceMessageId: source_message_id } : {}) }); wakeDelivery?.enqueue(wake); return councilMcpResult({ wake, delivery: wakeDelivery ? "scheduled" : "queued", note: wakeDelivery ? "CodexWeb scheduled an asynchronous ChatGPT Web resurrection turn for the target. Target-private context is delivered only inside the wake engine." : "The wake is durable; configure Full MCP/tunnel mode to enable automatic delivery." }); });
}
