import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import * as z from "zod/v4";
import { CouncilStore } from "./store";
import { actorSchema, agentIdSchema, councilMcpResult, messageIdSchema, roomIdSchema, type CouncilWakeDelivery, type ResolveCouncilActor } from "./mcp-shared";
export function registerCouncilWorkTools(server: McpServer, store: CouncilStore, resolveActor: ResolveCouncilActor, wakeDelivery?: CouncilWakeDelivery): void {
  server.registerTool("council_decide", { title: "Record final Council policy", description: "Record a deliberated policy with rationale, accepted/rejected arguments and unresolved risks.", inputSchema: { ...actorSchema, room_id: roomIdSchema, title: z.string().trim().min(1).max(240), policy: z.string().trim().min(1).max(12_000), rationale: z.string().trim().min(1).max(12_000), accepted_arguments: z.array(z.string().trim().min(1).max(2_000)).max(64).default([]), rejected_arguments: z.array(z.string().trim().min(1).max(2_000)).max(64).default([]), unresolved_risks: z.array(z.string().trim().min(1).max(2_000)).max(64).default([]) }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, room_id, title, policy, rationale, accepted_arguments, rejected_arguments, unresolved_risks }, extra) => { const actor = resolveActor(extra, agent_id); return councilMcpResult({ decision: store.decide({ roomId: room_id, createdByAgentId: actor, title, policy, rationale, acceptedArguments: accepted_arguments, rejectedArguments: rejected_arguments, unresolvedRisks: unresolved_risks }) }); });
  server.registerTool("council_task_create", { title: "Create Council work item", description: "Create a concrete task resulting from deliberation and optionally assign it to a named agent.", inputSchema: { ...actorSchema, room_id: roomIdSchema, title: z.string().trim().min(1).max(240), description: z.string().trim().min(1).max(8_000), assignee_agent_id: agentIdSchema.optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, room_id, title, description, assignee_agent_id }, extra) => { const actor = resolveActor(extra, agent_id); return councilMcpResult({ task: store.createTask({ roomId: room_id, createdByAgentId: actor, title, description, ...(assignee_agent_id ? { assigneeAgentId: assignee_agent_id } : {}) }) }); });
  server.registerTool("council_task_update", { title: "Update Council work item", description: "Claim, advance, block, review or complete a Council task.", inputSchema: { ...actorSchema, task_id: z.string().trim().min(1).max(128), status: z.enum(["todo", "claimed", "in_progress", "review", "done", "blocked"]), assignee_agent_id: agentIdSchema.optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false } }, async ({ agent_id, task_id, status, assignee_agent_id }, extra) => { const actor = resolveActor(extra, agent_id); return councilMcpResult({ task: store.updateTask({ taskId: task_id, actorAgentId: actor, status, ...(assignee_agent_id ? { assigneeAgentId: assignee_agent_id } : {}) }) }); });
  server.registerTool("council_wake", { title: "Wake another Council participant", description: "Durably target another named participant and asynchronously schedule a ChatGPT Web resurrection turn when the wake engine is available.", inputSchema: { ...actorSchema, target_agent_id: agentIdSchema, room_id: roomIdSchema, reason: z.string().trim().min(1).max(4_000), source_message_id: messageIdSchema.optional() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false } }, async ({ agent_id, target_agent_id, room_id, reason, source_message_id }, extra) => { const actor = resolveActor(extra, agent_id); const wake = store.wake({ targetAgentId: target_agent_id, sourceAgentId: actor, roomId: room_id, reason, ...(source_message_id ? { sourceMessageId: source_message_id } : {}) }); const context = store.buildContextPacket({ agentId: target_agent_id, roomId: room_id, wakeId: wake.id }); wakeDelivery?.enqueue(wake); return councilMcpResult({ wake, context, delivery: wakeDelivery ? "scheduled" : "queued", note: wakeDelivery ? "CodexWeb scheduled an asynchronous ChatGPT Web resurrection turn for the target." : "The wake is durable; configure Full MCP/tunnel mode to enable automatic delivery." }); });
}
